from __future__ import annotations

from pathlib import Path

from attribution_roi.attribution import attribution_summary, method_share_table
from attribution_roi.budget import budget_recommendation, scenario_summary, status_quo_cost
from attribution_roi.config import (
    FIGURES_DIR,
    NOTEBOOKS_DIR,
    OUTPUTS_DIR,
    REPORTS_DIR,
    SYNTHETIC_DATA_DIR,
    SYNTHETIC_TOUCHPOINTS_PATH,
)
from attribution_roi.data import (
    channel_touch_summary,
    data_quality_report,
    journey_pattern_summary,
    journey_table,
    load_touchpoints,
)
from attribution_roi.reporting import (
    write_data_quality_markdown,
    write_generation_markdown,
    write_json,
    write_strategy_deck,
    write_summary_report,
)
from attribution_roi.synthetic import SyntheticConfig, generate_synthetic_touchpoints, generation_assumptions
from attribution_roi.viz import (
    plot_attribution_comparison,
    plot_budget_gap,
    plot_conversion_rate_by_channel,
    plot_journey_length_distribution,
    plot_scenario_lift,
    plot_touchpoint_frequency,
)


def ensure_directories() -> None:
    for path in [SYNTHETIC_DATA_DIR, OUTPUTS_DIR, REPORTS_DIR, FIGURES_DIR, NOTEBOOKS_DIR]:
        path.mkdir(parents=True, exist_ok=True)


def generate_data(config: SyntheticConfig | None = None) -> None:
    ensure_directories()
    cfg = config or SyntheticConfig()
    touchpoints = generate_synthetic_touchpoints(cfg)
    touchpoints.to_csv(SYNTHETIC_TOUCHPOINTS_PATH, index=False)
    assumptions = generation_assumptions(cfg)
    write_json(OUTPUTS_DIR / "synthetic_generation_assumptions.json", assumptions)
    write_generation_markdown(OUTPUTS_DIR / "synthetic_generation_assumptions.md", assumptions)


def run_analysis() -> dict[str, object]:
    ensure_directories()
    touchpoints = load_touchpoints(SYNTHETIC_TOUCHPOINTS_PATH)
    journeys = journey_table(touchpoints)
    quality = data_quality_report(touchpoints)
    touch_summary = channel_touch_summary(touchpoints)
    patterns = journey_pattern_summary(journeys)
    attribution = attribution_summary(journeys)
    share_table = method_share_table(attribution)
    budget = budget_recommendation(attribution)
    scenarios = scenario_summary(budget)
    status_quo = status_quo_cost(budget)

    journeys.to_csv(OUTPUTS_DIR / "journey_summary.csv", index=False)
    touch_summary.to_csv(OUTPUTS_DIR / "touchpoint_summary.csv", index=False)
    patterns.to_csv(OUTPUTS_DIR / "journey_patterns.csv", index=False)
    attribution.to_csv(OUTPUTS_DIR / "attribution_summary.csv", index=False)
    share_table.to_csv(OUTPUTS_DIR / "attribution_method_share_table.csv", index=False)
    budget.to_csv(OUTPUTS_DIR / "budget_reallocation.csv", index=False)
    scenarios.to_csv(OUTPUTS_DIR / "scenario_summary.csv", index=False)
    write_json(OUTPUTS_DIR / "status_quo_cost.json", status_quo)
    write_data_quality_markdown(OUTPUTS_DIR / "data_quality_report.md", quality)

    plot_touchpoint_frequency(touch_summary, FIGURES_DIR)
    plot_conversion_rate_by_channel(touch_summary, FIGURES_DIR)
    plot_journey_length_distribution(journeys, FIGURES_DIR)
    plot_attribution_comparison(attribution, FIGURES_DIR)
    plot_budget_gap(budget, FIGURES_DIR)
    plot_scenario_lift(scenarios, FIGURES_DIR)

    return {
        "touchpoints": touchpoints,
        "journeys": journeys,
        "quality": quality,
        "touch_summary": touch_summary,
        "patterns": patterns,
        "attribution": attribution,
        "budget": budget,
        "scenarios": scenarios,
        "status_quo": status_quo,
    }


def build_reports(analysis: dict[str, object] | None = None) -> None:
    ensure_directories()
    if analysis is None:
        analysis = run_analysis()
    write_summary_report(
        REPORTS_DIR / "summary.md",
        analysis["quality"],
        analysis["touch_summary"],
        analysis["journeys"],
        analysis["attribution"],
        analysis["budget"],
        analysis["scenarios"],
        analysis["status_quo"],
    )
    write_strategy_deck(
        REPORTS_DIR / "strategy_deck.md",
        analysis["quality"],
        analysis["attribution"],
        analysis["budget"],
        analysis["scenarios"],
        analysis["status_quo"],
    )


def build_notebook(path: Path | None = None) -> None:
    import json

    ensure_directories()
    notebook_path = path or (NOTEBOOKS_DIR / "marketing_attribution_analysis.ipynb")
    cells = [
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "# Marketing Channel Attribution & Budget ROI Analysis\n",
                "\n",
                "This notebook accompanies the repo pipeline. The data is synthetic and generated by `scripts/generate_data.py`.\n",
            ],
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "from pathlib import Path\n",
                "import pandas as pd\n",
                "\n",
                "PROJECT_ROOT = Path('..').resolve()\n",
                "touchpoints = pd.read_csv(PROJECT_ROOT / 'data' / 'synthetic' / 'customer_journeys.csv', parse_dates=['touchpoint_date'])\n",
                "touch_summary = pd.read_csv(PROJECT_ROOT / 'outputs' / 'touchpoint_summary.csv')\n",
                "journeys = pd.read_csv(PROJECT_ROOT / 'outputs' / 'journey_summary.csv')\n",
                "attribution = pd.read_csv(PROJECT_ROOT / 'outputs' / 'attribution_summary.csv')\n",
                "budget = pd.read_csv(PROJECT_ROOT / 'outputs' / 'budget_reallocation.csv')\n",
                "scenarios = pd.read_csv(PROJECT_ROOT / 'outputs' / 'scenario_summary.csv')\n",
                "touchpoints.head()\n",
            ],
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## Phase 1: Explore Journeys\n",
                "\n",
                "The first checks document class balance, journey length, channel mix, and descriptive conversion rates.\n",
            ],
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "summary = {\n",
                "    'touchpoint_rows': len(touchpoints),\n",
                "    'journeys': journeys['journey_id'].nunique(),\n",
                "    'conversion_rate': journeys['converted'].mean(),\n",
                "    'avg_journey_length': journeys['journey_length'].mean(),\n",
                "}\n",
                "summary\n",
            ],
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "touch_summary.sort_values('touchpoints', ascending=False)\n",
            ],
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## Phase 2: Attribution Model Comparison\n",
                "\n",
                "First-touch, last-touch, linear, and Markov removal-effect attribution allocate the same converted revenue pool differently.\n",
            ],
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "attribution.pivot(index='channel', columns='method', values='credit_share').style.format('{:.1%}')\n",
            ],
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "![Attribution model comparison](../reports/figures/attribution_model_comparison.png)\n",
                "\n",
                "![Budget gap to Markov](../reports/figures/budget_gap_to_markov.png)\n",
            ],
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## Phase 3: Strategy Scenarios\n",
                "\n",
                "The scenarios translate Markov-informed credit into staged budget options. They are decision framing, not causal proof.\n",
            ],
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": ["scenarios\n"],
        },
    ]
    notebook = {
        "cells": cells,
        "metadata": {
            "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python", "pygments_lexer": "ipython3"},
        },
        "nbformat": 4,
        "nbformat_minor": 5,
    }
    notebook_path.write_text(json.dumps(notebook, indent=2), encoding="utf-8")


def run_all() -> dict[str, object]:
    generate_data()
    analysis = run_analysis()
    build_reports(analysis)
    build_notebook()
    return analysis
